const tradeLanes = [
    {
        id: 1,
        from: "China",
        fromShort: "CN",
        toShort: "US",
        to: "USA",
    },
    {
        id: 2,
        from: "China",
        fromShort: "CN",
        toShort: "ZA",
        to: "South Africa",
    },
    {
        id: 3,
        from: "China",
        fromShort: "CN",
        toShort: "DE",
        to: "Germany",
    },
    {
        id: 4,
        from: "China",
        fromShort: "CN",
        toShort: "NG",
        to: "Nigeria",
    },
    {
        id: 5,
        from: "China",
        fromShort: "CN",
        toShort: "IN",
        to: "India",
    },
    {
        id: 6,
        from: "China",
        fromShort: "CN",
        toShort: "NL",
        to: "Netherlands",
    },
    {
        id: 7,
        from: "China",
        fromShort: "CN",
        toShort: "FR",
        to: "France",
    },
    {
        id: 8,
        from: "USA",
        fromShort: "US",
        toShort: "CN",
        to: "China",
    },
    {
        id: 9,
        from: "USA",
        fromShort: "US",
        toShort: "ZA",
        to: "South Africa",
    },
    {
        id: 10,
        from: "USA",
        fromShort: "US",
        toShort: "DE",
        to: "Germany",
    },
    {
        id: 11,
        from: "USA",
        fromShort: "US",
        toShort: "NG",
        to: "Nigeria",
    },
    {
        id: 12,
        from: "USA",
        fromShort: "US",
        toShort: "IN",
        to: "India",
    },
    {
        id: 13,
        from: "USA",
        fromShort: "US",
        toShort: "NL",
        to: "Netherlands",
    },
    {
        id: 14,
        from: "USA",
        fromShort: "US",
        toShort: "FR",
        to: "France",
    },
    {
        id: 15,
        from: "India",
        fromShort: "IN",
        toShort: "CN",
        to: "China",
    },
    {
        id: 16,
        from: "India",
        fromShort: "IN",
        toShort: "ZA",
        to: "South Africa",
    },
    {
        id: 17,
        from: "India",
        fromShort: "IN",
        toShort: "DE",
        to: "Germany",
    },
    {
        id: 18,
        from: "India",
        fromShort: "IN",
        toShort: "NG",
        to: "Nigeria",
    },
    {
        id: 19,
        from: "India",
        fromShort: "IN",
        toShort: "US",
        to: "USA",
    },
    {
        id: 20,
        from: "India",
        fromShort: "IN",
        toShort: "NL",
        to: "Netherlands",
    },
    {
        id: 21,
        from: "India",
        fromShort: "IN",
        toShort: "FR",
        to: "France",
    },
    {
        id: 22,
        from: "South Africa",
        fromShort: "ZA",
        toShort: "CN",
        to: "China",
    },
    {
        id: 23,
        from: "South Africa",
        fromShort: "ZA",
        toShort: "IN",
        to: "India",
    },
    {
        id: 24,
        from: "South Africa",
        fromShort: "ZA",
        toShort: "DE",
        to: "Germany",
    },
    {
        id: 25,
        from: "South Africa",
        fromShort: "ZA",
        toShort: "NG",
        to: "Nigeria",
    },
    {
        id: 26,
        from: "South Africa",
        fromShort: "ZA",
        toShort: "US",
        to: "USA",
    },
    {
        id: 27,
        from: "South Africa",
        fromShort: "ZA",
        toShort: "NL",
        to: "Netherlands",
    },
    {
        id: 28,
        from: "South Africa",
        fromShort: "ZA",
        toShort: "FR",
        to: "France",
    },
    {
        id: 29,
        from: "Germany",
        fromShort: "DE",
        toShort: "CN",
        to: "China",
    },
    {
        id: 30,
        from: "Germany",
        fromShort: "DE",
        toShort: "IN",
        to: "India",
    },
    {
        id: 31,
        from: "Germany",
        fromShort: "DE",
        toShort: "ZA",
        to: "South Africa",
    },
    {
        id: 32,
        from: "Germany",
        fromShort: "DE",
        toShort: "NG",
        to: "Nigeria",
    },
    {
        id: 33,
        from: "Germany",
        fromShort: "DE",
        toShort: "US",
        to: "USA",
    },
    {
        id: 34,
        from: "Germany",
        fromShort: "DE",
        toShort: "NL",
        to: "Netherlands",
    },
    {
        id: 35,
        from: "Germany",
        fromShort: "DE",
        toShort: "FR",
        to: "France",
    },
    {
        id: 36,
        from: "Nigeria",
        fromShort: "NG",
        toShort: "CN",
        to: "China",
    },
    {
        id: 37,
        from: "Nigeria",
        fromShort: "NG",
        toShort: "IN",
        to: "India",
    },
    {
        id: 38,
        from: "Nigeria",
        fromShort: "NG",
        toShort: "ZA",
        to: "South Africa",
    },
    {
        id: 39,
        from: "Nigeria",
        fromShort: "NG",
        toShort: "DE",
        to: "Germany",
    },
    {
        id: 40,
        from: "Nigeria",
        fromShort: "NG",
        toShort: "US",
        to: "USA",
    },
    {
        id: 41,
        from: "Nigeria",
        fromShort: "NG",
        toShort: "NL",
        to: "Netherlands",
    },
    {
        id: 42,
        from: "Nigeria",
        fromShort: "NG",
        toShort: "FR",
        to: "France",
    },
    {
        id: 43,
        from: "Netherlands",
        fromShort: "NL",
        toShort: "CN",
        to: "China",
    },
    {
        id: 44,
        from: "Netherlands",
        fromShort: "NL",
        toShort: "IN",
        to: "India",
    },
    {
        id: 45,
        from: "Netherlands",
        fromShort: "NL",
        toShort: "ZA",
        to: "South Africa",
    },
    {
        id: 46,
        from: "Netherlands",
        fromShort: "NL",
        toShort: "DE",
        to: "Germany",
    },
    {
        id: 47,
        from: "Netherlands",
        fromShort: "NL",
        toShort: "US",
        to: "USA",
    },
    {
        id: 48,
        from: "Netherlands",
        fromShort: "NL",
        toShort: "NG",
        to: "Nigeria",
    },
    {
        id: 49,
        from: "Netherlands",
        fromShort: "NL",
        toShort: "FR",
        to: "France",
    },
    {
        id: 50,
        from: "France",
        fromShort: "FR",
        toShort: "CN",
        to: "China",
    },
    {
        id: 51,
        from: "France",
        fromShort: "FR",
        toShort: "IN",
        to: "India",
    },
    {
        id: 52,
        from: "France",
        fromShort: "FR",
        toShort: "ZA",
        to: "South Africa",
    },
    {
        id: 53,
        from: "France",
        fromShort: "FR",
        toShort: "DE",
        to: "Germany",
    },
    {
        id: 54,
        from: "France",
        fromShort: "FR",
        toShort: "US",
        to: "USA",
    },
    {
        id: 55,
        from: "France",
        fromShort: "FR",
        toShort: "NG",
        to: "Nigeria",
    },
    {
        id: 56,
        from: "France",
        fromShort: "FR",
        toShort: "NL",
        to: "Netherlands",
    },
];

export default tradeLanes;
