export const settingsConstant = {
    FETCH_ROLES: "FETCH_ROLES",
    FETCH_ROLE: "FETCH_ROLE",
    UPDATE_ROLE: "UPDATE_ROLE",
    DELETE_ROLE: "UPDATE_ROLE",
    FETCH_TEAM_MEMBERS: "FETCH_TEAM_MEMBERS",
    FETCH_WALLET_BALANCE: "FETCH_WALLET_BALANCE",
    FETCH_WALLET: "FETCH_WALLET",
    FETCH_WALLET_HISTORY: "FETCH_WALLET_HISTORY",
};
